Changed include from <yaml.h> to "yaml.h"
If yaml.h has been installed system-wide, conflicts will occur (see error below).
```
api.c:810:19: error: conflicting types for 'yaml_alias_event_initialize'
yaml_alias_event_initialize(yaml_event_t *event, const yaml_char_t *anchor)
                  ^
/usr/local/include/yaml.h:555:1: note: previous declaration is here
yaml_alias_event_initialize(yaml_event_t *event, yaml_char_t *anchor);
^
api.c:834:1: error: conflicting types for 'yaml_scalar_event_initialize'
yaml_scalar_event_initialize(yaml_event_t *event,
^
/usr/local/include/yaml.h:580:1: note: previous declaration is here
yaml_scalar_event_initialize(yaml_event_t *event,
^
api.c:888:1: error: conflicting types for 'yaml_sequence_start_event_initialize'
yaml_sequence_start_event_initialize(yaml_event_t *event,
^
/usr/local/include/yaml.h:603:1: note: previous declaration is here
yaml_sequence_start_event_initialize(yaml_event_t *event,
^
api.c:943:1: error: conflicting types for 'yaml_mapping_start_event_initialize'
yaml_mapping_start_event_initialize(yaml_event_t *event,
^
/usr/local/include/yaml.h:635:1: note: previous declaration is here
yaml_mapping_start_event_initialize(yaml_event_t *event,
^
api.c:1208:1: error: conflicting types for 'yaml_document_add_scalar'
yaml_document_add_scalar(yaml_document_t *document,
^
/usr/local/include/yaml.h:898:1: note: previous declaration is here
yaml_document_add_scalar(yaml_document_t *document,
^
api.c:1258:1: error: conflicting types for 'yaml_document_add_sequence'
yaml_document_add_sequence(yaml_document_t *document,
^
/usr/local/include/yaml.h:915:1: note: previous declaration is here
yaml_document_add_sequence(yaml_document_t *document,
^
api.c:1303:1: error: conflicting types for 'yaml_document_add_mapping'
yaml_document_add_mapping(yaml_document_t *document,
^
/usr/local/include/yaml.h:931:1: note: previous declaration is here
yaml_document_add_mapping(yaml_document_t *document,
^
7 errors generated.
```